In [1]:
import sqlite3
from sqlite3 import Error
import csv
import pandas as pd
SHOW = True

In [2]:
df = pd.read_csv('US_Accidents_Dec20_updated.csv')
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-2716600,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.10891,-83.09286,40.11206,-83.03187,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2716601,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.86542,-84.06280,39.86501,-84.04873,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-2716602,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.10266,-84.52468,39.10209,-84.52396,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-2716603,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.10148,-84.52341,39.09841,-84.52241,0.219,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
4,A-2716604,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.06213,-81.53784,41.06217,-81.53547,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516059,A-4239402,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.00248,-117.37936,33.99888,-117.37094,0.543,At Market St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1516060,A-4239403,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.76696,-117.14806,32.76555,-117.15363,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1516061,A-4239404,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.77545,-117.84779,33.77740,-117.85727,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,False,Day,Day,Day,Day
1516062,A-4239405,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.99246,-118.40302,33.98311,-118.39565,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1516063,A-4239406,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.13393,-117.23092,34.13736,-117.23934,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [5]:
df = df[df['State']=='OH']
df1 = df[['Severity','Zipcode','Weather_Condition']]
df1 = df1.dropna()
df1['Zipcode'] = df1['Zipcode'].str.slice(stop=5)
df1 = df1.dropna()
df1['Weather_Condition'] = df1['Weather_Condition'].map({'Light Rain': 1, 'Overcast': 2, 'Fair': 0, 'Thunder': 3, 'Partly Cloudy': 4,'Mostly Cloudy': 5, 'Snow': 6, 'Light Snow': 7, 'Snow': 8, 'Clear': 9})

NameError: name 'd1' is not defined

In [6]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5, random_state=0).fit(df1)
kmeans.labels_

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [5]:
connection = None
try:
    connection = sqlite3.connect("projecttest")
    connection.text_factory = str
except Error as e:
    print("Error occurred: " + str(e))

In [44]:
connection.execute("DROP TABLE IF EXISTS overall;")
def part_ai_1(connection):
    part_ai_1_sql = "CREATE TABLE overall(id string, severity integer, start_time datetime, end_time datatime, start_lat real, start_lng real, end_lat real, end_lng real, distance real, description string, number integer, street string, side string, city string, state string, county string, zipcode string, country string, timezone string, airport_code string, weather_time datetime, temperature real, wind real, humidity integer, pressure real, visibility real, wind_direction string, wind_speed real, precipitation real, weather_cond string, amenity boolean, bump boolean, corssing, boolean, give_way boolean, junction boolean, no_exit boolean, roundabout boolean, station boolean, stop boolean, traffic_calm boolean, traffic_sig boolean, turning_loop boolean, sunrise string, civil string, nautical string, astronomical string);"
    c = connection.execute(part_ai_1_sql)
    return c

In [45]:
r = part_ai_1(connection)
print(r.fetchall())

[]

In [46]:
with open('US_Accidents_Dec20_updated.csv') as m:
    reader = csv.reader(m)
    data = list(reader)
for i in data:
    connection.execute("INSERT INTO overall VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);", (i[0], i[1], i[2], i[3], i[4], i[5], i[6], i[7], i[8], i[9], i[10], i[11], i[12], i[13], i[14], i[15], i[16], i[17], i[18], i[19], i[20], i[21], i[22], i[23], i[24], i[25], i[26], i[27], i[28], i[29], i[30], i[31], i[32], i[33], i[34], i[35], i[36], i[37], i[38], i[39], i[40], i[41], i[42], i[43], i[44], i[45], i[46]))

In [47]:
s = "SELECT * FROM overall"
c = connection.execute(s)
print(c.fetchall())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)